version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install deps
          command: |
            sudo bash maintenance/install_deps.sh
      - run:
          name: Install compiler deps
          command: |
            sudo bash maintenance/install_compiler_deps.sh
      - run:
          name: Setup python
          command: |
            sudo bash maintenance/setup_python.sh
